### ISSUE TITLE
"Tomorrow" word not properly displayed in the "List" item.

### ISSUE THREAD

**Issue by Quintus24** [AmProsius/gothic-1-community-patch#256]
Hello, everyone!

I would like to report the following bug:

**Describe the bug:**
The issue can be encountered once the user initiates the "**Test of Faith**" quest and acquires the "**List**" item from **Ian**, in the **Old Mine**.
The last sentence is displayed as "_We're expecting the delivery for the day after **tomo**_".
The "**tomorrow**" word is not fully displayed on the page.

**Expected behavior:**
The word "**tomo**" is properly displayed as "**tomorrow**".

**Steps to reproduce the issue:**
1. Initiate and progress through the "**Test of Faith**" quest.
2. Travel to the **Old Mine** and receive the "**List**" item from **Ian**.
3. Open the "**List**", read it and notice the "_We're expecting the delivery for the day after **tomo**_".
4. Travel to the **New Camp** and give the "**List**" to **Lares**.
5. Receive the new "**List (extended)**" item from **Lares**.
6. Open the "**List (extended)**", read it and notice the "**tomo**" word.

**Additional context**
Issue occurs for both "**List**" and "**List (extended)**" items.
The resolution of the device used is set as **1366x768x32**, in case it's relevant.

_Attaching screenshots for more clear information_.

1. The "**List**" before **Lares**.
![List before Lares](https://user-images.githubusercontent.com/93062373/146691361-3c3c1307-a203-4778-9823-dbac6ba24de9.JPG)

2. The "**List (extended)**" after **Lares**.
![List after Lares](https://user-images.githubusercontent.com/93062373/146691391-ffe7bbaf-6eb1-46e5-9c9f-70d230d5b103.JPG)

3. The "**List (extended)**" item in the inventory.
![List (extended)](https://user-images.githubusercontent.com/93062373/146691412-e937e456-6ffb-4981-9df4-ca79b30202a4.JPG)

Thank You and Best Regards!
Quintus24

**Comment by AmProsius** [comment]
This might be related to #252 .

**Comment by szapp** [comment]
There may be very many such problems. A lot of different font-patches ("large font", "HD font", ...) are available alongside interface scaling through Union or SystemPack. This here issue could also just by caused by any of these.

This may be a never ending problem. These should not individually fixed in that case, but rather at their origin, e.g. implement automatic line breaks (or similar) in documents, inventory description and dialog choices. That, however, would have to be implemented efficiently to not hit performance.

In the end, since this bug/issue does not arise from Gothic itself but is caused by third party patches/tools, I'd give it low priority.

**Comment by Quintus24** [comment]
> This here issue could also just by caused by any of these.

Hi, guys, 

It's possible that these string issues simply occur on my side because I use a small screen device to play the game.
Unfortunately, I lack the resources to check on anything else, therefore, I risk opening false positives bug reports for them.
If they do not occur on larger monitors, it's probably safe to close the issues as expected behavior.

Regards,
Quintus24

**Comment by szapp** [comment]
> It's possible that these string issues simply occur on my side because I use a small screen device to play the game. 

Yes, I assume you are either using the SystemPack or Union (judging by the rotating items in the inventory your the screenshots). They scale the interface (i.e. health and focus bars and font sizes) to the resolution, which is set to enabled by default.

You may disable that scaling in the `SystemPack.ini` in the `[GothicPath]/System/` directory by changing the setting `Scale` in the section `[INTERFACE]` to `0`. (Not sure about the exact name of the option.)

If you feel like trying that, you can report here if the mentioned issue is resolved by it.

@AmProsius On a more technical side, we have the ability to check for that scaling and also find out the exact scaling factor with [Bar_GetInterfaceScaling](https://github.com/Lehona/LeGo/blob/2c7aa0eab917bdf1304fceeee0d87bdefa5e847b/Bars.d#L273-L281). However, I am not exactly sure what to do with that information. It may be better to ignore any scaling, but instead implement line wrapping within views, which could turn out very complicated (and requiring a machine code implementation for sufficient performance).

**Comment by Quintus24** [comment]
Hi, @szapp,

> You may disable that scaling in the `SystemPack.ini` in the `[GothicPath]/System/` directory by changing the setting `Scale` in the section `[INTERFACE]` to `0`. (Not sure about the exact name of the option.)

I tried this, but no changes were observed, issues still occur, also rechecked #252.

> Yes, I assume you are either using the SystemPack or Union

I'm not very familiar with the SystemPack or Union, but I play the game on **Steam**, the Piranha Bytes folks updated it recently and officially added the **SystemPack** to it.
Other than that, I don't use other mods or patches, just the **G1CP** project that you folks are working on, the latest version.

Regards,
Quintus24
